import dotenv from 'dotenv';
import connectDB from '../config/db.js';
import Job from '../models/Job.js';
import User from '../models/User.js';

dotenv.config();

const jobs=[
  {title:'Software Developer',company:'Nexora Technologies',location:'Bengaluru, India',description:'Build reliable web products with a collaborative engineering team, contributing across planning, implementation, and continuous improvement.',requirements:['Bachelor’s degree in computer science or equivalent practical experience','1+ years of professional software development experience','Strong problem-solving and communication skills'],responsibilities:['Develop and maintain production web application features','Write tested, maintainable code and participate in peer reviews','Work with product and design partners to deliver iterative improvements'],salary:'₹6–10 LPA',jobType:'Full-Time',experienceLevel:'Entry',skills:['JavaScript','React','Node.js','Git'],deadline:'2027-01-31'},
  {title:'Frontend Developer',company:'PixelCraft Studio',location:'Mumbai, India',description:'Create polished, accessible user experiences for customer-facing SaaS products.',requirements:['2+ years building responsive web interfaces','Solid knowledge of modern JavaScript and component-based UI development','Attention to visual quality and accessibility'],responsibilities:['Implement responsive interfaces from design specifications','Collaborate with designers to refine interaction details','Improve frontend performance, quality, and accessibility'],salary:'₹7–12 LPA',jobType:'Full-Time',experienceLevel:'Mid',skills:['React','TypeScript','CSS','HTML','REST APIs'],deadline:'2027-02-15'},
  {title:'Backend Developer',company:'CloudSprint Systems',location:'Hyderabad, India',description:'Design and operate secure backend services that support high-volume recruitment and workflow products.',requirements:['2+ years of backend development experience','Experience designing REST APIs and working with databases','Understanding of authentication, validation, and service reliability'],responsibilities:['Build and maintain scalable API endpoints','Model data and optimize database access patterns','Diagnose production issues and improve observability'],salary:'₹8–14 LPA',jobType:'Full-Time',experienceLevel:'Mid',skills:['Node.js','Express','MongoDB','REST APIs','Docker'],deadline:'2027-02-28'},
  {title:'Full Stack Developer',company:'Launchpad Labs',location:'Pune, India',description:'Own product features end to end, from intuitive interfaces to dependable APIs and data models.',requirements:['3+ years of full stack development experience','Experience with a modern frontend framework and Node.js services','Ability to translate product requirements into technical solutions'],responsibilities:['Deliver end-to-end features across frontend and backend','Partner with stakeholders during discovery and release planning','Maintain code quality through testing and code reviews'],salary:'₹10–16 LPA',jobType:'Full-Time',experienceLevel:'Mid',skills:['React','Node.js','MongoDB','JavaScript','Git'],deadline:'2027-03-15'},
  {title:'Data Analyst',company:'InsightBridge Analytics',location:'Chennai, India',description:'Turn operational and product data into clear analysis that helps teams make better decisions.',requirements:['Bachelor’s degree in a quantitative field or equivalent experience','Strong SQL and spreadsheet skills','Ability to communicate findings clearly to non-technical audiences'],responsibilities:['Build recurring reports and self-service dashboards','Analyze trends, funnels, and business performance','Partner with teams to define reliable metrics'],salary:'₹5–9 LPA',jobType:'Full-Time',experienceLevel:'Entry',skills:['SQL','Excel','Power BI','Python','Data Visualization'],deadline:'2027-01-20'},
  {title:'UI/UX Designer',company:'Northstar Digital',location:'Remote',description:'Shape simple, thoughtful product experiences for a growing suite of people operations tools.',requirements:['Portfolio demonstrating end-to-end product design work','Experience with user research, wireframing, and prototyping','Strong visual design and communication skills'],responsibilities:['Conduct discovery and turn insights into user flows','Create wireframes, prototypes, and production-ready UI specifications','Work with engineers to ensure high-quality implementation'],salary:'₹6–11 LPA',jobType:'Remote',experienceLevel:'Mid',skills:['Figma','User Research','Wireframing','Prototyping','Design Systems'],deadline:'2027-02-10'},
  {title:'HR Executive',company:'PeopleFirst Services',location:'New Delhi, India',description:'Support a positive employee experience across recruitment coordination, onboarding, and core HR operations.',requirements:['Bachelor’s degree in human resources, business, or a related field','1+ years of HR or recruitment coordination experience','Excellent organization and interpersonal communication'],responsibilities:['Coordinate interviews, offers, and onboarding activities','Maintain accurate employee and candidate records','Support employee engagement and HR policy communication'],salary:'₹4–7 LPA',jobType:'Full-Time',experienceLevel:'Entry',skills:['Recruitment','Onboarding','HR Operations','Communication','MS Office'],deadline:'2027-01-25'},
  {title:'DevOps Engineer',company:'OrbitScale Infrastructure',location:'Bengaluru, India',description:'Improve the speed, reliability, and security of engineering delivery through modern cloud and automation practices.',requirements:['3+ years of DevOps, SRE, or infrastructure engineering experience','Hands-on experience with cloud platforms and CI/CD pipelines','Strong scripting and incident troubleshooting skills'],responsibilities:['Build and maintain CI/CD pipelines and infrastructure automation','Monitor services and improve availability and performance','Partner with developers on secure, repeatable deployment practices'],salary:'₹12–18 LPA',jobType:'Full-Time',experienceLevel:'Senior',skills:['AWS','Docker','Kubernetes','CI/CD','Terraform','Linux'],deadline:'2027-03-01'}
];

await connectDB();
const admin=await User.findOne({role:'admin'}).select('_id');
if(!admin)throw new Error('Create an admin account before running the job seed.');

let inserted=0;
for(const job of jobs){
  const exists=await Job.exists({title:job.title,company:job.company});
  if(!exists){await Job.create({...job,createdBy:admin._id});inserted+=1;}
}

console.log(`Demo jobs seed complete: ${inserted} created, ${jobs.length-inserted} already present.`);
process.exit(0);
